export interface CompanyResult {
  id: string;
  search_id: string;
  company_name: string;
  full_company_name: string | null;
  inn: string | null;
  kpp: string | null;
  ogrn: string | null;
  status: string | null;
  region: string | null;
  city: string | null;
  address: string | null;
  okved_main: string | null;
  okved_description: string | null;
  revenue: number | null;
  revenue_raw: string | null;
  employees_count: number | null;
  registration_date: string | null;
  company_age: number | null;
  website: string | null;
  phone: string | null;
  email: string | null;
  summary_text: string | null;
  has_website: boolean;
  vacancies_total: number;
  sales_vacancies: number;
  marketing_vacancies: number;
  business_type: string;
  source_name: string;
  source_url: string | null;
  raw_snapshot_id: string | null;
  icp_score: number | null;
  icp_is_match: boolean | null;
  icp_confidence: "low" | "medium" | "high" | null;
  icp_fit_reason: string | null;
  icp_mismatch_reason: string | null;
  icp_matched_criteria: string[] | null;
  icp_failed_criteria: string[] | null;
  icp_recommended_action: "add_to_results" | "manual_review" | "skip" | null;
  llm_model: string | null;
  llm_scored_at: string | null;
  comment: string | null;
  created_at: string;
}
